# Generated by Django 4.1.5 on 2023-01-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_inventorysales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventorySales',
        ),
    ]
