# Generated by Django 4.1.5 on 2023-01-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0009_sales_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='quantity',
            new_name='quantity_sold',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='price',
        ),
    ]
