# Generated by Django 4.1.5 on 2023-01-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0010_rename_quantity_sales_quantity_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity_sold',
            field=models.IntegerField(null=True),
        ),
    ]
