# Generated by Django 4.1.5 on 2023-01-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0011_alter_inventory_quantity_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
