# Generated by Django 4.1.5 on 2023-01-20 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0012_alter_inventory_quantity_sold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_loaded', models.IntegerField()),
                ('load_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.inventory')),
            ],
        ),
    ]
