# Generated by Django 4.1.5 on 2023-01-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0013_stockload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='date',
            new_name='sold_date',
        ),
    ]
