# Generated by Django 4.1.5 on 2023-01-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0015_rename_quantity_sold_sales_qty_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='product',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stockload',
            old_name='product',
            new_name='name',
        ),
    ]
