# Generated by Django 4.1.5 on 2023-01-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0016_rename_product_sales_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='unit_of_measure',
            field=models.CharField(choices=[('kom', 'kom'), ('kg', 'kg'), ('lit', 'lit')], default='kom', max_length=3),
        ),
    ]
